######################################################################
# Automatically generated by qmake (3.0) Thu Sep 22 12:50:20 2016
######################################################################

TEMPLATE = app
TARGET = bigint
INCLUDEPATH += .

# Input
SOURCES += main.cpp
